# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# 使用python-embed版時要加這2行，才能import本地module
import sys, os
sys.path.append(os.path.dirname(__file__))
from model import *

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 659)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.commitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.commitBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.commitBtn.setFont(font)
        self.commitBtn.setObjectName("commitBtn")
        self.horizontalLayout_2.addWidget(self.commitBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.horizontalLayout_2.addWidget(self.result)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.keywordsList = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.keywordsList.setFont(font)
        self.keywordsList.setObjectName("keywordsList")
        # item = QtWidgets.QListWidgetItem()
        # self.keywordsList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.keywordsList.addItem(item)
        self.gridLayout.addWidget(self.keywordsList, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categorySelect = QtWidgets.QComboBox(self.centralwidget)
        self.categorySelect.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.categorySelect.setFont(font)
        self.categorySelect.setObjectName("categorySelect")
        # self.categorySelect.addItem("")
        # self.categorySelect.addItem("")
        self.horizontalLayout.addWidget(self.categorySelect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.testArticle = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.testArticle.setFont(font)
        self.testArticle.setObjectName("testArticle")
        self.gridLayout.addWidget(self.testArticle, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文章比對"))
        self.commitBtn.setText(_translate("MainWindow", "比對"))
        __sortingEnabled = self.keywordsList.isSortingEnabled()
        self.keywordsList.setSortingEnabled(False)
        # item = self.keywordsList.item(0)
        # item.setText(_translate("MainWindow", "#A"))
        # item = self.keywordsList.item(1)
        # item.setText(_translate("MainWindow", "#B"))
        self.keywordsList.setSortingEnabled(__sortingEnabled)
        # self.categorySelect.setItemText(0, _translate("MainWindow", "美妝"))
        # self.categorySelect.setItemText(1, _translate("MainWindow", "運動"))
        # -------------------------  以上為qt designer自動生成部分  -------------------------
        self.setCategory()
    
    
    def setCategory(self):
        # 載入model
        loadModel()
        
        # 先刪掉category所有的類別選項
        self.categorySelect.clear()
        # 根據資料庫中的category種類，設定左上角選單中的類別選項名稱(ex: 美妝, 運動, ...)
        for category in getCategory():
            self.categorySelect.addItem(category)
        
        # 剛開啟程式時，設定關鍵字
        self.setKeywords(self.categorySelect.currentText())
        # 更改類別選項時，也要連動更改成該類別的關鍵字
        self.categorySelect.currentTextChanged.connect(self.setKeywords)
        # 文章送出的按鈕按下
        self.commitBtn.clicked.connect(self.submit)
    
    # 設定右方關鍵字
    def setKeywords(self, category):
        _translate = QtCore.QCoreApplication.translate
        # 先刪掉keywordsList所有的關鍵字
        self.keywordsList.clear()
        # 再依照所選類別，一一加回去
        for keyword in getKeywords(category):
            item = QtWidgets.QListWidgetItem()
            item.setText(_translate("MainWindow", keyword))
            self.keywordsList.addItem(item)
    
    # 文章送出的按鈕按下
    def submit(self):
        self.commitBtn.setEnabled(False)
        category= self.categorySelect.currentText()
        testArticle= self.testArticle.toPlainText()
        self.result.setText(compare(category, testArticle))
        self.commitBtn.setEnabled(True)
        



        # -------------------------  以下為qt designer自動生成部分  -------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
